sudo: false
language: minimal

before_script:
  - curl -sO https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh

script:
  - bash release.sh
  - bash release.sh -g 1.13.2

branches:
  only:
    - /^[vV]?\d+\.\d+(\.\d+)?(-\S*)?$/
